name: Go

on:
  push:
    tags:
      - v*
    branches: 
      - main
  pull_request:
    tags:
      - v*
    branches: 
      - main

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    strategy:
      matrix:
        go_version: [ "1.18" ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version:  ${{ matrix.go_version }}
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.47.3

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: '-exclude=G304,G401,G404,G501,G502,G503,G504,G505 ./...'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
