name: Go

on:
  push:
    tags:
      - v*
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.29
    
    - name: Run Gosec Security Scanner
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get github.com/securego/gosec/cmd/gosec
        gosec ./...
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
